db.following.insert({alias:"10gen", name:"10gen", site:"http://www.10gen.com"});
db.following.insert({alias:"Hwaet", name:"Kyle Banker", site:"http://kylebanker.com/blog"});
db.following.insert({alias:"mongodb", name:"mongodb", site:"http://mongodb.org"});
db.following.insert({alias:"hazarddesign", name:"Ivan Carrasco", site:"http://hazarddesign.tumblr.com"});
db.following.insert({alias:"pythonperu", name:"Python Peru", site:"http://www.python.pe"});
db.following.insert({alias:"luizdev", name:"luis", site:""});
db.following.insert({alias:"develCuy", name:"Fernando P. Garcia", site:"http://develcuy.com/en/about"});
db.following.insert({alias:"vladimirestrada", name:"Vladimir Estrada", site:"http://vladimirestrada.blogspot.com"});
db.following.insert({alias:"JoshPeru", name:"Josh Huerta", site:"http://www.myspace.com/joshperu"});
db.following.insert({alias:"ictecpe", name:"ICTEC", site:"http://ictec.biz"});
db.following.insert({alias:"Dries", name:"Dries Buytaert", site:"http://www.buytaert.net"});
db.following.insert({alias:"gvanrossum", name:"Guido van Rossum", site:"http://python.org/~guido/"});
db.following.insert({alias:"joindiaspora", name:"Diaspora", site:"http://diasporaproject.org"});
db.following.insert({alias:"app_engine", name:"Google App Engine", site:"http://code.google.com/appengine"});
db.following.insert({alias:"gesysistemas", name:"Gestion y Sistemas", site:"http://gestionysistemas.com"});
db.following.insert({alias:"cesarmmg", name:"cesar miranda", site:"http://atthecloud.blogspot.com"});
db.following.insert({alias:"idperunet", name:"idPERU - Internet", site:"http://www.idperu.net"});
db.following.insert({alias:"obarriga", name:"Oscar Barriga", site:"http://www.oscarbarriga.net"});
db.following.insert({alias:"ALEXIsystem", name:"Alexsys", site:"http://alexiespinoza.wordpress.com"});
db.following.insert({alias:"||JoTa||", name:"JoTa Caro Salazar"});
db.following.insert({alias:"alfonsodg", name:"Alfonso de la Guarda", site:"http://alfonsodg.blogspot.com"});
db.following.insert({alias:"Gustavo_Veliz", name:"Gustavo_Veliz", site:"http://blog.gustavoveliz.com"});
db.following.insert({alias:"spolsky", name:"Joel Spolsky", site:"http://www.joelonsoftware.com"});